title: "mccamon.org"
author: "Mike McCamon"
description: "Nothing special going on here"
permalink: /:title/
lang: "en"
excerpt_separator: "<!-- more -->"
date_format: "%B %d, %Y"

# Layout
sidebar: false               # show a sidebar instead of the usual header
show_excerpts: true         # show article excerpts on the home page
show_related: true           # show the previous and next links after every post
show_description: true       # show the site description in the sidebar
show_title: true            # always keep the site title visible

# Styling
dark_header: false           # always keep the header dark
minimal: true               # use simpler style

collectons:
  authors:
    output: true

# Menu
navigation:
  - {file: "index.html", icon: home}
  - {file: "blog.md"}
  - {file: "mike.md" }
  - {file: "jody.md" }


external:                    # see http://fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:mike@Mccamon.org"}
  - {title: Github, icon: github, url: "https://github.com/mccamon/contrast"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""      # see https://disqus.com/
#  isso_domain: ""           # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 - jekyll-paginate
 
 # pageinate
paginate: 5
paginate_path: "blog/page:num/"
